version: '2'
services:
    cs499p2-app:
        image: cs499p2
        external_links:
            - cs499p2-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/cs499p2?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    cs499p2-mysql:
        extends:
            file: mysql.yml
            service: cs499p2-mysql
